Add mobile detection
contao/package-metadata pull request #343
Opened 2021-01-27 10:57 UTC by marcel-mathias-nolte

2021-01-27 11:22 UTC, aschempp reviewed
Die Erweiterung marcel-mathias-nolte/contao-jquery-in-backend/ hört sich nach etwas an, welches nicht über den Contao Manager installiert wird, sondern eine Abhängigkeit für andere ist, sehe ich das richtig?

2021-01-27 11:28 UTC, marcel-mathias-nolte commented
Normalerweise schon - Aber derzeit sind bei meinem AG viele aus Contao 3 mitgenommene Erweiterungen im Einsatz, die noch nicht als Contao 4 Bundle umgesetzt wurden, aber jQuery im Backend vorraussetzen. Leider ist es immer müselig die Erweiterungen mit composer require manuell hinzuzufügen, deswegen ein extra Package. Somit können diese alten Erweiterungen nicht einfach die Abhängigkeit über composer auflösen.

2021-01-29 08:15 UTC, aschempp requested changes

2021-01-29 08:15 UTC, aschempp commented on linter/allowlists/de.txt
> +Mobilgerät
dieses Wort scheint nirgends in der Beschreibung vorhanden zu sein

2021-02-01 06:08 UTC, marcel-mathias-nolte commented
Ja, war aus Reflex (Einzahl/Mehrzahl). Mein Fehler. Korrigiert.

2021-02-14 08:34 UTC, aschempp requested changes
Der `homepage` key scheint mir ungültig (und unnötig), er liefert ja keine Informationen zum Paket? In der Erweiterungsliste (https://extensions.contao.org) wird entweder auf die Homepage oder auf Packagist verlinkt, diese Homepage-URL würde für einen Nutzer keinen Mehrwert bieten?

2021-04-14 09:01 UTC, Toflar commented
I'm closing this because there has been no activity and I keep getting reminded about the review of this.
Feel free to ping us if you intend to continue working on this PR so we can reopen it.

2021-04-14 09:01 UTC, closed without merging