extension added
contao/package-metadata pull request #346
Opened 2021-02-08 09:44 UTC by heimseiten

2021-02-15 06:17 UTC, aschempp commented
Please fix the linter issues to get this merged.

2021-02-15 09:51 UTC, heimseiten commented
sadly it is not possible, because "TinySlider", "Tiny Slider" or "Tiny-Slider" do not work in the title :/

2021-02-15 10:01 UTC, fritzmg commented
You need to add that to the default allow list.

2021-02-15 11:21 UTC, heimseiten commented
Thanks fritzmg! That would be awesome, but I can't find a place to do this.

2021-02-15 11:22 UTC, fritzmg commented
The file is located [here](https://github.com/contao/package-metadata/blob/main/linter/allowlists/default.txt). You need to edit that file in your PR and commit and push your changes.

2021-02-15 11:32 UTC, heimseiten commented
Thanks again. I added "Tiny Slider" in the default.txt

2021-03-25 09:01 UTC, aschempp commented
Please fix the remaining validation issues

2021-03-31 09:00 UTC, aschempp commented
@heimseiten can you please fix the validation issues?

2021-03-31 09:56 UTC, heimseiten commented
I would like to do that, but i don't know how. I think first the request for default.txt would have to be accepted to pass the spell checker, right?

2021-03-31 10:03 UTC, fritzmg commented
@heimseiten the word "Tiny" needs to be added to the default allow list. You added "Tiny Slider", but that won't do anything as these are actually two words.

2021-03-31 10:23 UTC, heimseiten commented
Thank you very much and please excuse me. I never had to deal with the spell checker before.

2021-03-31 10:35 UTC, fritzmg requested changes

2021-03-31 10:35 UTC, fritzmg commented on linter/allowlists/default.txt
> +standard
Why did you add this to the default allow list? It should be removed.

2021-03-31 10:35 UTC, fritzmg commented on meta/heimseiten/contao-tiny-slider-bundle/de.yml
> +        Ersetzt den standard Contao-Slider mit dem Tiny Slider und fügt Funktionen hinzu wie Fade, Ken-Burns-Effekt usw..
```suggestion
        Ersetzt den Standard Contao-Slider mit dem Tiny Slider und fügt Funktionen hinzu wie Fade, Ken-Burns-Effekt usw..
```

There is no adjective called "standard" in German, is there? Afaik you always capitalise it, when using it this way.

2021-03-31 10:40 UTC, fritzmg approved these changes

2021-04-01 09:06 UTC, Toflar approved these changes

2021-04-01 09:06 UTC, merged