Added isotope/payment-skrill
contao/package-metadata pull request #491
Opened 2023-08-16 09:46 UTC by aschempp

2023-08-16 09:52 UTC, Toflar commented
https://github.com/contao/package-metadata/actions/runs/5877229494/job/15936934642?pr=491 need to be addressed.

2023-08-23 09:39 UTC, Toflar requested changes
Ping :)

2023-08-23 10:05 UTC, MDevster submitted a review, later dismissed

2023-08-27 20:56 UTC, xchs approved these changes

2023-08-28 07:23 UTC, Toflar approved these changes

2023-08-28 07:23 UTC, merged